name: 'Build Windows'
description: 'Build ths packages for Windows package'
runs:
  using: "composite"
  steps:
    # Prepare Visual Studio
    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    # --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Xerces-C - setup
    - name: Xerces-C - prepare
      shell: cmd
      run: |
        mkdir xerces-c
        cd xerces-c
        curl -o xerces-c.zip https://dlcdn.apache.org//xerces/c/3/sources/xerces-c-3.3.0.zip
        tar -xf xerces-c.zip --strip-components=1

    # Xerces-C - build MD
    - name: Xerces-C - configure
      working-directory: xerces-c
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX:PATH=libs -DCMAKE_CXX_FLAGS="/DWIN32 /D_WINDOWS -O2 -Ob2 -DNDEBUG" -DCMAKE_C_FLAGS="/DWIN32 /D_WINDOWS /W3" -DBUILD_SHARED_LIBS:BOOL=FALSE -Dxmlch-type=wchar_t

    - name: Xerces-C - build MinSizeRel
      working-directory: xerces-c/build
      shell: cmd
      run: |
        msbuild /m ALL_BUILD.vcxproj /p:Configuration=MinSizeRel
        msbuild /m INSTALL.vcxproj /p:Configuration=MinSizeRel

    - name: Xerces-C - build Debug
      working-directory: xerces-c/build
      shell: cmd
      run: |
        msbuild /m ALL_BUILD.vcxproj /p:Configuration=Debug
        msbuild /m INSTALL.vcxproj /p:Configuration=Debug

    # Xerces-C - build MT
    - name: Xerces-C - configure [MT]
      working-directory: xerces-c
      shell: cmd
      run: |
        mkdir build_mt
        cd build_mt
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX:PATH=libs -DCMAKE_CXX_FLAGS_DEBUG="/MTd /Zi /Ob0 /Od /RTC1" -DCMAKE_CXX_FLAGS_MINSIZEREL="/MT /O1 /Ob1 /DNDEBUG" -DCMAKE_C_FLAGS_DEBUG="/MTd /Zi /Ob0 /Od /RTC1" -DCMAKE_C_FLAGS_MINSIZEREL="/MT /O1 /Ob1 /DNDEBUG" -DCMAKE_C_FLAGS="/DWIN32 /D_WINDOWS /W3" -DBUILD_SHARED_LIBS:BOOL=FALSE -Dxmlch-type=wchar_t

    - name: Xerces-C - build MinSizeRel [MT]
      working-directory: xerces-c/build_mt
      shell: cmd
      run: |
        msbuild /m ALL_BUILD.vcxproj /p:Configuration=MinSizeRel
        msbuild /m INSTALL.vcxproj /p:Configuration=MinSizeRel

    - name: Xerces-C - build Debug [MT]
      working-directory: xerces-c/build_mt
      shell: cmd
      run: |
        msbuild /m ALL_BUILD.vcxproj /p:Configuration=Debug
        msbuild /m INSTALL.vcxproj /p:Configuration=Debug

    # --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Boost - setup and build
    - name: Boost - prepare
      shell: cmd
      run: |
          mkdir boost
          cd boost
          curl -o boost.zip https://archives.boost.io/release/1.86.0/source/boost_1_86_0.zip
          tar -xf boost.zip --strip-components=1

    # --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # libMVRGdtf - setup
    - name: libMVRGdtf - checkout repository
      uses: actions/checkout@v4
      with:
        path: libMvrGdtf

    # --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: libMVRGdtf [MD_NO_MZ] - configure
      working-directory: libMvrGdtf
      shell: cmd
      run: |
        mkdir build_MD_NO_MZ
        cd build_MD_NO_MZ
        cmake .. -DCMAKE_INSTALL_PREFIX:PATH=libs -DWIN_RUNTIME_LIB=-MD -DXERCES_INCLUDE_PATH="..\xerces-c\build\libs\include;..\xerces\src" -DXERCES_LIB_PATH="..\xerces\build\libs\lib" -DXERCES_ROOT_PATH="..\xerces-c" -DDO_NOT_INCLUDE_MINI_ZIP=TRUE
        ren MvrGdtf.vcxproj MvrGdtf_ORG.vcxproj

    # libMVRGdtf - build Debug
    - name: libMVRGdtf [MD_NO_MZ] - Debug - add lib dependencies
      working-directory: libMvrGdtf/build_MD_NO_MZ
      shell: pwsh
      run: |
        $xml = [xml](Get-Content MvrGdtf_ORG.vcxproj)
        $xml.Project.ItemDefinitionGroup | ForEach-Object {
          $node = $xml.CreateElement("AdditionalDependencies", "http://schemas.microsoft.com/developer/msbuild/2003")
          $node.InnerText = 'iphlpapi.lib;..\..\xerces-c\build\libs\lib\xerces-c_3D.lib;mdns_cpp\lib\Debug\mdns_cpp.lib;%(AdditionalDependencies)'
          $_.Lib.AppendChild($node) | Out-Null
        }
        Set-Content -Path "MvrGdtf.vcxproj" -Value $xml.OuterXml
      
    - name: libMVRGdtf [MD_NO_MZ] - compile Debug
      working-directory: libMvrGdtf/build_MD_NO_MZ
      shell: cmd
      run: |
        msbuild /m ALL_BUILD.vcxproj /p:Configuration=Debug
        msbuild /m INSTALL.vcxproj /p:Configuration=Debug

    # libMVRGdtf - build MinSizeRel
    - name: libMVRGdtf [MD_NO_MZ] - MinSizeRel - add lib dependencies
      working-directory: libMvrGdtf/build_MD_NO_MZ
      shell: pwsh
      run: |
        $xml = [xml](Get-Content MvrGdtf_ORG.vcxproj)
        $xml.Project.ItemDefinitionGroup | ForEach-Object {
          $node = $xml.CreateElement("AdditionalDependencies", "http://schemas.microsoft.com/developer/msbuild/2003")
          $node.InnerText = 'iphlpapi.lib;..\..\xerces-c\build\libs\lib\xerces-c_3.lib;mdns_cpp\lib\MinSizeRel\mdns_cpp.lib;%(AdditionalDependencies)'
          $_.Lib.AppendChild($node) | Out-Null
        }
        Set-Content -Path "MvrGdtf.vcxproj" -Value $xml.OuterXml

    - name: libMVRGdtf [MD_NO_MZ] - compile MinSizeRel
      working-directory: libMvrGdtf/build_MD_NO_MZ
      shell: cmd
      run: |
        msbuild /m ALL_BUILD.vcxproj /p:Configuration=MinSizeRel
        msbuild /m INSTALL.vcxproj /p:Configuration=MinSizeRel

    # --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: libMVRGdtf [MD] - configure
      working-directory: libMvrGdtf
      shell: cmd
      run: |
        mkdir build_MD
        cd build_MD
        cmake .. -DCMAKE_INSTALL_PREFIX:PATH=libs -DWIN_RUNTIME_LIB=-MD -DXERCES_INCLUDE_PATH="..\xerces-c\build\libs\include;..\xerces\src" -DXERCES_LIB_PATH="..\xerces\build\libs\lib" -DXERCES_ROOT_PATH="..\xerces-c\build"
        ren MvrGdtf.vcxproj MvrGdtf_ORG.vcxproj

    # libMVRGdtf - build Debug
    - name: libMVRGdtf [MD] - Debug - add lib dependencies
      working-directory: libMvrGdtf/build_MD
      shell: pwsh
      run: |
        $xml = [xml](Get-Content MvrGdtf_ORG.vcxproj)
        $xml.Project.ItemDefinitionGroup | ForEach-Object {
          $node = $xml.CreateElement("AdditionalDependencies", "http://schemas.microsoft.com/developer/msbuild/2003")
          $node.InnerText = 'iphlpapi.lib;..\..\xerces-c\build\libs\lib\xerces-c_3D.lib;mdns_cpp\lib\Debug\mdns_cpp.lib;%(AdditionalDependencies)'
          $_.Lib.AppendChild($node) | Out-Null
        }
        Set-Content -Path "MvrGdtf.vcxproj" -Value $xml.OuterXml
      
    - name: libMVRGdtf [MD] - compile Debug
      working-directory: libMvrGdtf/build_MD
      shell: cmd
      run: |
        msbuild /m ALL_BUILD.vcxproj /p:Configuration=Debug
        msbuild /m INSTALL.vcxproj /p:Configuration=Debug

    # libMVRGdtf - build MinSizeRel
    - name: libMVRGdtf [MD] - MinSizeRel - add lib dependencies
      working-directory: libMvrGdtf/build_MD
      shell: pwsh
      run: |
        $xml = [xml](Get-Content MvrGdtf_ORG.vcxproj)
        $xml.Project.ItemDefinitionGroup | ForEach-Object {
          $node = $xml.CreateElement("AdditionalDependencies", "http://schemas.microsoft.com/developer/msbuild/2003")
          $node.InnerText = 'iphlpapi.lib;..\..\xerces-c\build\libs\lib\xerces-c_3.lib;mdns_cpp\lib\MinSizeRel\mdns_cpp.lib;%(AdditionalDependencies)'
          $_.Lib.AppendChild($node) | Out-Null
        }
        Set-Content -Path "MvrGdtf.vcxproj" -Value $xml.OuterXml

    - name: libMVRGdtf [MD] - compile MinSizeRel
      working-directory: libMvrGdtf/build_MD
      shell: cmd
      run: |
        msbuild /m ALL_BUILD.vcxproj /p:Configuration=MinSizeRel
        msbuild /m INSTALL.vcxproj /p:Configuration=MinSizeRel

    # --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: libMVRGdtf [MT] - configure
      working-directory: libMvrGdtf
      shell: cmd
      run: |
        mkdir build_MT
        cd build_MT
        cmake .. -DCMAKE_INSTALL_PREFIX:PATH=libs -DWIN_RUNTIME_LIB=-MT -DXERCES_INCLUDE_PATH="..\xerces-c\build_mt\libs\include;..\xerces\src" -DXERCES_LIB_PATH="..\xerces\build_mt\libs\lib" -DXERCES_ROOT_PATH="..\xerces-c\build_mt"
        ren MvrGdtf.vcxproj MvrGdtf_ORG.vcxproj

    # libMVRGdtf - build Debug
    - name: libMVRGdtf [MT] - Debug - add lib dependencies
      working-directory: libMvrGdtf/build_MT
      shell: pwsh
      run: |
        $xml = [xml](Get-Content MvrGdtf_ORG.vcxproj)
        $xml.Project.ItemDefinitionGroup | ForEach-Object {
          $node = $xml.CreateElement("AdditionalDependencies", "http://schemas.microsoft.com/developer/msbuild/2003")
          $node.InnerText = 'iphlpapi.lib;..\..\xerces-c\build_mt\libs\lib\xerces-c_3D.lib;mdns_cpp\lib\Debug\mdns_cpp.lib;%(AdditionalDependencies)'
          $_.Lib.AppendChild($node) | Out-Null
        }
        Set-Content -Path "MvrGdtf.vcxproj" -Value $xml.OuterXml
      
    - name: libMVRGdtf [MT] - compile Debug
      working-directory: libMvrGdtf/build_MT
      shell: cmd
      run: |
        msbuild /m ALL_BUILD.vcxproj /p:Configuration=Debug
        msbuild /m INSTALL.vcxproj /p:Configuration=Debug

    # libMVRGdtf - build MinSizeRel
    - name: libMVRGdtf [MT] - MinSizeRel - add lib dependencies
      working-directory: libMvrGdtf/build_MT
      shell: pwsh
      run: |
        $xml = [xml](Get-Content MvrGdtf_ORG.vcxproj)
        $xml.Project.ItemDefinitionGroup | ForEach-Object {
          $node = $xml.CreateElement("AdditionalDependencies", "http://schemas.microsoft.com/developer/msbuild/2003")
          $node.InnerText = 'iphlpapi.lib;..\..\xerces-c\build_mt\libs\lib\xerces-c_3.lib;mdns_cpp\lib\MinSizeRel\mdns_cpp.lib;%(AdditionalDependencies)'
          $_.Lib.AppendChild($node) | Out-Null
        }
        Set-Content -Path "MvrGdtf.vcxproj" -Value $xml.OuterXml

    - name: libMVRGdtf [MT] - compile MinSizeRel
      working-directory: libMvrGdtf/build_MT
      shell: cmd
      run: |
        msbuild /m ALL_BUILD.vcxproj /p:Configuration=MinSizeRel
        msbuild /m INSTALL.vcxproj /p:Configuration=MinSizeRel

    # --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: libMVRGdtf - Generate output library
      working-directory: libMvrGdtf
      shell: pwsh
      run: |
        if (Test-Path -Path "output") {
          Remove-Item -Path "output" -Recurse -Force
        }
        New-Item -Path "output\libMvrGdtf\lib" -ItemType Directory -Force
        Copy-Item -Path "libs\MinSizeRel\*" -Destination "output\libMvrGdtf\lib" -Recurse
        Copy-Item -Path "libs\Debug\*" -Destination "output\libMvrGdtf\lib" -Recurse

        New-Item -Path "output\libMvrGdtf\include" -ItemType Directory -Force
        Copy-Item -Path "src\Include\*" -Destination "output\libMvrGdtf\include" -Recurse
        
        if (Test-Path -Path "libs\MinSizeRel") {
          Remove-Item -Path "libs\MinSizeRel" -Recurse -Force
        }
          
        if (Test-Path -Path "libs\Debug") {
          Remove-Item -Path "libs\Debug" -Recurse -Force
        }
