//-----------------------------------------------------------------------------
//----- Copyright deersoft 2015 - 2017 www.deersoft.de
//-----------------------------------------------------------------------------
#include "Prefix/StdAfx.h"

////////////////////////////////////////////////////////////////
// Plug-in specific
#define VWParaLightingDevice_CLASSNAME			"Lighting Device"
#define VWParaLightingDevice_P_Symbol			"Symbol Name"
#define VWParaLightingDevice_P_NAME				"Inst Type"
#define VWParaLightingDevice_P_Position			"Position"
#define VWParaLightingDevice_P_Focus			"Focus"
#define VWParaLightingDevice_P_Symbol			"Symbol Name"
#define VWParaLightingDevice_P_GoboData			"Gobo Data"
#define VWParaLightingDevice_P_ColorData		"Color Data"
#define VWParaLightingDevice_P_AniWheel			"Color Flag Data"
#define VWParaLightingDevice_P_LitFileName		"Fixture Mode"
#define VWParaLightingDevice_P_CountDmxChannels "Num Channels"
#define VWParaLightingDevice_P_Color			"RGBColor"

#define VWParaLightingDevice_P_AdditionalRotX	"xRot"
#define VWParaLightingDevice_P_AdditionalRotY	"yRot"
#define VWParaLightingDevice_P_AdditionalRotZ	"zRot"
#define VWParaLightingDevice_P_UseAdditionalRot "Rotate3DPosition"
#define VWParaLightingDevice_P_EnableZRot		"EnableZRot"


// Fields developed for GDTF
#define VWParaLightingDevice_P_CieColor			"GDTF CIE Color"
#define VWParaLightingDevice_P_GdtfName			"GDTF Fixture Name"
#define VWParaLightingDevice_P_GdtfMode			"GDTF Fixture Mode"
#define VWParaLightingDevice_P_CustomId			"GDTF Fixture Custom ID"
#define VWParaLightingDevice_P_FixtureTypeId	"GDTF Fixture Type ID"

// Fields that need to be matched
#define VWParaLightingDevice_P_FixtureId		"FixtureId"
#define VWParaLightingDevice_P_UnitNumber		"Unit Number"
#define VWParaLightingDevice_P_Address			"Dimmer"
#define VWParaLightingDevice_P_Universe			"Universe"

#define VWParaLightingPosition_CLASSNAME		"Light Position Obj"
#define VWParaLightingPosition_P_Name			"Position Name"



#define VWParaFocusPointObject_CLASSNAME		"Focus Point Object"
#define VWParaFocusPointObject_P_Name			"Name"

#define VWParaCurvedTruss_CLASSNAME				"Curved Truss"
#define VWParaCurvedTruss_P_Name				"Name"

#define VWParaTrussObj_CLASSNAME				"Straight Truss"
#define VWParaTrussObj_P_Name					"Name"

#define TrussItem_CLASSNAME						"TrussItem"
#define TrussItem_P_NAME						"Name"

#define VideoScreen_CLASSNAME					"Video Screen"

//----------------------------------------------------------------------------------------------------------------------------------
// SceneDataExchange XML Values
#define XML_Val_RootNodeName			"GeneralScenceDescription"
#define XML_Val_RootAttrMainVersion		"verMajor"
#define XML_Val_RootAttrMinorVersion	"verMinor"

#define XML_Val_UserDataNodeName		"UserData"
#define XML_Val_UserDataVWEntry			"VWEntry"
#define XML_Val_UserDataVWKeyAttr		"key"

#define XML_Val_DataNodeName			"Data"
#define XML_Val_DataNodeAttrVersion		"ver"
#define XML_Val_DataNodeAttrProvider	"provider"

#define XML_Val_SceneNodeName		"Scene"
#define XML_Val_AuxDataNodeName		"AUXData"
#define XML_Val_LayersNodeName		"Layers"

#define XML_Val_SymDefNodeName		"Symdef"

#define XML_Val_PositionNodeName	"Position"

#define XML_Val_ClassNodeName	"Class"

#define XML_Val_LayerObjectNodeName	"Layer"
#define XML_Val_FixtureNodeName		"Fixture"
#define XML_Val_GroupNodeName		"GroupObject"
#define XML_Val_ChildObsNodeName	"ChildList"

#define XML_Val_MatrixNodeName		"Matrix"
#define XML_Val_Matrix_U_NodeName	"U"
#define XML_Val_Matrix_V_NodeName	"V"
#define XML_Val_Matrix_W_NodeName	"W"
#define XML_Val_Matrix_O_NodeName	"O"

#define XML_Val_GeometriesNodeName		"Geometries"

#define XML_Val_NameAttrName		"name"
#define XML_Val_GuidAttrName		"uuid"
#define XML_Val_ClassingNodeName		"Classing"

#define XML_Val_FixtureGDTFSpec		"GDTFSpec"
#define XML_Val_FixtureDMXMode		"GDTFMode"
#define XML_Val_FixtureFocus		"Focus"
#define XML_Val_FixturePosition		"Position"
#define XML_Val_FixtureAddress		"Address"

#define XML_Val_FixtureAddresses	"Addresses"
#define XML_Val_FixtureFixtureID	"FixtureID"
#define XML_Val_FixtureUnitNumber	"UnitNumber"
#define XML_Val_FixtureColor		"Color"
#define XML_Val_FixtureAttrBreak	"break"
#define XML_Val_FixtureTypeId		"FixtureTypeId"
#define XML_Val_FixtureCustomid		"CustomId"

#define XML_Val_SceneObjectNodeName			"SceneObject"

#define XML_Val_FocusPointObjectNodeName	"FocusPoint"

#define XML_Val_TrussObjectNodeName			"Truss"

#define XML_Val_VideoScreenObjectNodeName	"VideoScreen"

#define XML_Val_SymbolObjectNodeName		"Symbol"
#define XML_Val_GuidSymdefAttrName			"symdef"

#define XML_Val_GeometryObjectNodeName		"Geometry3D"
#define XML_Val_GeometryObjectAttrFile		"fileName"

const Sint32 kMVR_MajorVersion = 1;
const Sint32 kMVR_MinorVersion = 4;

// ----------------------------------------------------------------------------------------------------------------------------------
// GDTF XML Values

#define XML_GDTF_GDTFFILENAME			"description.xml"

#define XML_GDTF_ROOTNODENAME			"GDTF"
#define XML_GDTF_ROOTNODEATTRVERSION	"DataVersion"
#define XML_GDTF_CurrentVersion			"0.9"

#define XML_GDTF_FixtureNodeName		"FixtureType"
#define XML_GDTF_FixtureName			"Name"
#define XML_GDTF_FixtureShortName		"ShortName"
#define XML_GDTF_FixtureManufacturer	"Manufacturer"
#define XML_GDTF_FixtureDescription		"Description"
#define XML_GDTF_FixtureTypeID			"FixtureTypeID"
#define XML_GDTF_FixtureThumbnail		"Thumbnail"
#define XML_GDTF_LinkedUuid				"RefFT"

#define XML_GDTF_FixtureChildNodeAttributeDef		"AttributeDefinitions"
#define XML_GDTF_FixtureChildNodeActivationGroupDef	"ActivationGroups"
#define XML_GDTF_FixtureChildNodeFeatureGroupDef	"FeatureGroups"
#define XML_GDTF_FixtureChildNodeAttributesDef		"Attributes"

#define XML_GDTF_AttributeNode					"Attribute"
#define XML_GDTF_AttributeName					"Name"
#define XML_GDTF_AttributePrettyName			"Pretty"
#define XML_GDTF_AttributeActGroup				"ActivationGroup"
#define XML_GDTF_AttributeFeature				"Feature"
#define XML_GDTF_AttributefMainAttribute        "MainAttribute"
#define XML_GDTF_AttributePhysicalUnit          "PhysicalUnit"
#define XML_GDTF_AttributeColor                 "Color"

#define XML_GDTF_AttributeNoFeature_nullptr		    "NoFeature"

#define XML_GDTFPhysicalUnitEnum_None				"None"
#define XML_GDTFPhysicalUnitEnum_Percent			"Percent"
#define XML_GDTFPhysicalUnitEnum_Length				"Length"
#define XML_GDTFPhysicalUnitEnum_Mass				"Mass"
#define XML_GDTFPhysicalUnitEnum_Time				"Time"
#define XML_GDTFPhysicalUnitEnum_Temperatur			"Temperatur"
#define XML_GDTFPhysicalUnitEnum_LuminousItensity	"LuminousIntensity"
#define XML_GDTFPhysicalUnitEnum_Angle				"Angle"
#define XML_GDTFPhysicalUnitEnum_Force				"Force"
#define XML_GDTFPhysicalUnitEnum_Frequeny			"Frequency"
#define XML_GDTFPhysicalUnitEnum_Current			"Current"
#define XML_GDTFPhysicalUnitEnum_Voltage			"Voltage"
#define XML_GDTFPhysicalUnitEnum_Power				"Power"
#define XML_GDTFPhysicalUnitEnum_Energy				"Energy"
#define XML_GDTFPhysicalUnitEnum_Area				"Area"
#define XML_GDTFPhysicalUnitEnum_Volume				"Volume"
#define XML_GDTFPhysicalUnitEnum_Speed				"Speed"
#define XML_GDTFPhysicalUnitEnum_Acceleration		"Acceleration"
#define XML_GDTFPhysicalUnitEnum_AngularSpeed		"AngularSpeed"
#define XML_GDTFPhysicalUnitEnum_AngularAccc		"AngularAccc"
#define XML_GDTFPhysicalUnitEnum_WaveLength			"WaveLength"
#define XML_GDTFPhysicalUnitEnum_ColorComponent		"ColorComponent"

#define XML_EGdtfSpecialEnum_None			"Node"
#define XML_EGdtfSpecialEnum_Dimmer			"Dimmer"
#define XML_EGdtfSpecialEnum_Pan			"Pan"
#define XML_EGdtfSpecialEnum_Tilt			"Tilt"
#define XML_EGdtfSpecialEnum_X				"X"
#define XML_EGdtfSpecialEnum_Y				"Y"
#define XML_EGdtfSpecialEnum_Z				"Z"
#define XML_EGdtfSpecialEnum_RGB			"RGB"
#define XML_EGdtfSpecialEnum_Hue			"Hue"
#define XML_EGdtfSpecialEnum_Saturation		"Saturation"
#define XML_EGdtfSpecialEnum_Brightness		"Brightness"
#define XML_EGdtfSpecialEnum_ColorWheel		"ColorWheel"
#define XML_EGdtfSpecialEnum_Focus			"Focus"
#define XML_EGdtfSpecialEnum_Zoom			"Zoom"
#define XML_EGdtfSpecialEnum_Dummy			"Dummy"

#define XML_GDTF_ActivationGroupNode				"ActivationGroup"
#define XML_GDTF_ActivationGroupName				"Name"

#define XML_GDTF_FeatureGroupNode					"FeatureGroup"
#define XML_GDTF_FeatureGroupName					"Name"
#define XML_GDTF_FeatureGroupPrettyName				"Pretty"

#define XML_GDTF_FeatureNode					"Feature"
#define XML_GDTF_FeatureName					"Name"

#define XML_GDTF_FixtureChildNodeWheels				"Wheels"
#define XML_GDTF_FixtureChildNodeModels				"Models"
#define XML_GDTF_FixtureChildNodeGeomertries		"Geometries"
#define XML_GDTF_FixtureChildNodeDMX				"DMXModes"
#define XML_GDTF_FixtureChildNodeRevisions			"Revisions"
#define XML_GDTF_FixtureChildNodePresets			"FTPresets"
#define XML_GDTF_FixtureChildNodeMacros				"FTMacros"
#define XML_GDTF_FixtureChildNodePhysicalDesrip		"PhysicalDescriptions"
#define XML_GDTF_FixtureChildNodeRDM				"FTRDM"

#define XML_GDTF_WheelNodeName			"Wheel"
#define XML_GDTF_WheelName				"Name"

#define XML_GDTF_WheelSlotNodeName		"Slot"
#define XML_GDTF_WheelSlotName			"Name"
#define XML_GDTF_WheelSlotColor			"Color"
#define XML_GDTF_WheelSlotPicture		"MediaFileName"

#define XML_GDTF_PrismFacetNodeName		"Facet"
#define XML_GDTF_PrismFacetColor		"Color"
#define XML_GDTF_PrismFacetRotation		"Rotation"


#define XML_GDTF_ModelNodeName			"Model"
#define XML_GDTF_ModelName				"Name"
#define XML_GDTF_ModelLength			"Length"
#define XML_GDTF_ModelWidth				"Width"
#define XML_GDTF_ModelHeight			"Height"
#define XML_GDTF_ModelPrimitiveType		"PrimitiveType"
#define XML_GDTF_ModelFile				"File"

#define XML_GDTF_PrimitiveTypeEnum_Undefined	"Undefined"
#define XML_GDTF_PrimitiveTypeEnum_Cube			"Cube"
#define XML_GDTF_PrimitiveTypeEnum_Cylinder		"Cylinder"
#define XML_GDTF_PrimitiveTypeEnum_Sphere		"Sphere"
#define XML_GDTF_PrimitiveTypeEnum_Base			"Base"
#define XML_GDTF_PrimitiveTypeEnum_Yoke			"Yoke"
#define XML_GDTF_PrimitiveTypeEnum_Head			"Head"
#define XML_GDTF_PrimitiveTypeEnum_Scanner		"Scanner"
#define XML_GDTF_PrimitiveTypeEnum_Conventional	"Conventional"
#define XML_GDTF_PrimitiveTypeEnum_Pigtail	    "Pigtail"

#define XML_GDTF_GeometryNodeName				"Geometry"
#define XML_GDTF_GeometryName					"Name"
#define XML_GDTF_GeometryModelRef				"Model"
#define XML_GDTF_GeometryMatrix					"Position"

#define XML_GDTF_GeometryAxisNodeName			"Axis"
#define XML_GDTF_GeometryAxisFrom				"From"
#define XML_GDTF_GeometryAxisTo					"To"
#define XML_GDTF_GeometryAxisSpeed				"Speed"

#define XML_GDTF_FilterBeamNodeName				"FilterBeam"

#define XML_GDTF_FilterColorNodeName			"FilterColor"

#define XML_GDTF_FilterGoboNodeName				"FilterGobo"

#define XML_GDTF_FilterShaperNodeName			"FilterShaper"

#define XML_GDTF_LampNodeName					"Beam"
#define XML_GDTF_LampLampType					"LampType"
#define XML_GDTF_LampPowerConsumption			"PowerConsumption"
#define XML_GDTF_LampLuminousIntensity			"LuminousIntensity"
#define XML_GDTF_ColorTemperature				"ColorTemperature"
#define XML_GDTF_BeamAngle						"BeamAngle"
#define XML_GDTF_BeamRadius						"BeamRadius"
#define XML_GDTF_FieldAngle						"FieldAngle"
#define XML_GDTF_BeamType						"BeamType"
#define XML_GDTF_BeamColorRenderingIndex        "ColorRenderingIndex"				

#define XML_GDTF_BeamTypeEnum_Wash				"Wash"
#define XML_GDTF_BeamTypeEnum_Spot				"Spot"
#define XML_GDTF_BeamTypeEnum_None				"None"



#define XML_GDTF_LampTypeEnum_Discharge			"Discharge"
#define XML_GDTF_LampTypeEnum_Tungsten			"Tungsten"
#define XML_GDTF_LampTypeEnum_Halogen			"Halogen"
#define XML_GDTF_LampTypeEnum_LED				"LED"

#define XML_GDTF_BreakNodeName					"Break"
#define XML_GDTF_BreakDMXBreak					"DMXBreak"
#define XML_GDTF_BreakOffset					"DMXOffset"

#define XML_GDTF_GeometryReferenceNodeName		"GeometryReference"
#define XML_GDTF_GeometryReferenceLinkedGeo     "Geometry"


#define XML_GDTF_DMXModeNodeName				"DMXMode"
#define XML_GDTF_DMXModeName					"Name"
#define XML_GDTF_DMXModeGeometryRef				"Geometry"
#define XML_GDTF_DMXModeDMXChannels				"DMXChannels"
#define XML_GDTF_DMXModeRelations				"Relations"

#define XML_GDTF_DMXChannelNodeName				"DMXChannel"
#define XML_GDTF_DMXChannelDMXBreak				"DMXBreak"
#define XML_GDTF_DMXChannelCoarse				"Coarse"
#define XML_GDTF_DMXChannelFine					"Fine"
#define XML_GDTF_DMXChannelUltra				"Ultra"
#define XML_GDTF_DMXChannelUber                 "Uber"
#define XML_GDTF_DMXChannelDefault				"Default"
#define XML_GDTF_DMXChannelHighlight			"Highlight"
#define XML_GDTF_DMXChannelGeometry				"Geometry"

#define XML_GDTF_DMXFChannel_NONEVALUE			    "None"
#define XML_GDTF_DMXChannelDMXBreak_OverwriteValue	"Overwrite"

#define XML_GDTF_DMXFrequencyEnum_60			"60"
#define XML_GDTF_DMXFrequencyEnum_30			"30"
#define XML_GDTF_DMXFrequencyEnum_15			"15"
#define XML_GDTF_DMXFrequencyEnum_Slow1			"Slow1"
#define XML_GDTF_DMXFrequencyEnum_Slow2			"Slow2"
#define XML_GDTF_DMXFrequencyEnum_Slow3			"Slow3"

#define XML_GDTF_DMXLogicalChannelNodeName		"LogicalChannel"
#define XML_GDTF_DMXLogicalChannelAttribute		"Attribute"
#define XML_GDTF_DMXLogicalChannelSnap			"Snap"
#define XML_GDTF_DMXLogicalChannelMaster		"Master"
#define XML_GDTF_DMXLogicalChannelMibFadeFrames		    "MibFade"
#define XML_GDTF_DMXLogicalChannelDMXChangeTimeLimit    "DMXChangeTimeLimit"


#define XML_GDTF_DMXSnapEnum_Yes				"Yes"
#define XML_GDTF_DMXSnapEnum_No					"No"
#define XML_GDTF_DMXSnapEnum_On					"On"
#define XML_GDTF_DMXSnapEnum_Off				"Off"

#define XML_GDTF_DMXChannelFuntionNodeName				"ChannelFunction"
#define XML_GDTF_DMXChannelFuntionName					"Name"
#define XML_GDTF_DMXChannelFuntionAttribute             "Attribute"
#define XML_GDTF_DMXChannelFuntionOriginalAttribute		"OriginalAttribute"
#define XML_GDTF_DMXChannelFuntionDMXFrom				"DMXFrom"
#define XML_GDTF_DMXChannelFuntionPhysicalFrom			"PhysicalFrom"
#define XML_GDTF_DMXChannelFuntionPhysicalTo			"PhysicalTo"
#define XML_GDTF_DMXChannelFuntionRealFade				"RealFade"
#define XML_GDTF_DMXChannelFuntionWheelRef				"Wheel"
#define XML_GDTF_DMXChannelEmitter						"Emitter"
#define XML_GDTF_DMXChannelDMXInvert					"DMXInvert"

#define XML_GDTF_DMXChannelFuntionModeMaster			"ModeMaster"
#define XML_GDTF_DMXChannelFuntionModeFrom				"ModeFrom"
#define XML_GDTF_DMXChannelFuntionModeTo				"ModeTo"

#define XML_GDTF_DMXChannelDmxnvertEnum_Yes				"Yes"
#define XML_GDTF_DMXChannelDmxInvertEnum_No				"No"

#define XML_GDTF_DMXMasterEnum_None						"None"
#define XML_GDTF_DMXMasterEnum_Grand					"Grand"
#define XML_GDTF_DMXMasterEnum_Group					"Group"


#define XML_GDTF_DMXChannelSetNodeName					"ChannelSet"
#define XML_GDTF_DMXChannelSetName						"Name"
#define XML_GDTF_DMXChannelSetDMXFrom					"DMXFrom"
#define XML_GDTF_DMXChannelSetDMXTo						"DMXTo"
#define XML_GDTF_DMXChannelSetPhysicalFrom				"PhysicalFrom"
#define XML_GDTF_DMXChannelSetPhysicalTo				"PhysicalTo"
#define XML_GDTF_DMXChannelSetWheelSlotIndexRef			"WheelSlotIndex"
// Macros
#define XML_GDTF_MacroNodeName							"FTMacro"
#define XML_GDTF_MacroName                              "Name"
#define XML_GDTF_MacroDMX                               "MacroDMX"  
#define XML_GDTF_MacroDMXStep                           "MacroDMXStep"
#define XML_GDTF_MacroDMXStepDuration                   "Duration"
#define XML_GDTF_MacroDMXValue                          "MacroDMXValue"
#define XML_GDTF_MacroDMXValue_AttrValue                "Value"
#define XML_GDTF_MacroDMXValue_AttrChannel              "DMXChannel"
#define XML_GDTF_MacroVisual                            "MacroVisual"
#define XML_GDTF_MacroVisualStep                        "MacroVisualStep"
#define XML_GDTF_MacroVisualStep_AttrDuration           "Duration"
#define XML_GDTF_MacroVisualStep_AttrFade               "Fade"
#define XML_GDTF_MacroVisualStep_AttrDelay              "Delay"
#define XML_GDTF_MacroVisualValue                       "MacroVisualValue"
#define XML_GDTF_MacroVisualValue_AttrValue             "Value"
#define XML_GDTF_MacroVisualValue_AttrChanFunc          "ChannelFunction"
//
#define XML_GDTF_DMXRelationNodeName					"Relation"
#define XML_GDTF_DMXRelationName						"Name"
#define XML_GDTF_DMXRelationMaster						"Master"
#define XML_GDTF_DMXRelationSlave						"Follower"
#define XML_GDTF_DMXRelationType						"Type"
#define XML_GDTF_DMXRelationDMXFrom						"DMXFrom"
#define XML_GDTF_DMXRelationDMXTo						"DMXTo"

#define XML_GDTF_DMXMasterEnum_Multiply					"Multiply"
#define XML_GDTF_DMXMasterEnum_Override					"Override"

#define XML_GDTF_RevisionNodeName						"Revision"
#define XML_GDTF_RevisionText							"Text"
#define XML_GDTF_RevisionDate							"Date"
// -------------------------------------------------------------------------------
// Protocolls
#define XML_GDTF_Protocols                              "Protocols"

#define XML_GDTF_FTRDM                                  "FTRDM"
#define XML_GDTF_FTRDM_AttrManufacturerID               "ManufacturerID"
#define XML_GDTF_FTRDM_AttrDeviceModelID                "DeviceModelID"
#define XML_GDTF_FTRDM_AttrSoftwareVersionIDs           "SoftwareVersionIDs"

#define XML_GDTF_RDMParameterS                          "RDMParameters"
#define XML_GDTF_RDMParameter                           "RDMParameter"
#define XML_GDTF_RDMParam_AttrName                      "Name"
#define XML_GDTF_RDMParam_AttrPID                       "PID"
#define XML_GDTF_RDMParam_AttrType                      "Type"
#define XML_GDTF_RDMParam_AttrDataType                  "DataType"
#define XML_GDTF_RDMParam_AttrCommand                   "Command"
#define XML_GDTF_RDMParam_AttrSensorUnit                "SensorUnit"
#define XML_GDTF_RDMParam_AttrSensorUnitPrefix          "SensorUnitPrefix"
#define XML_GDTF_RDMParam_AttrMinValue                  "MinValue"
#define XML_GDTF_RDMParam_AttrMaxValue                  "MaxValue"
#define XML_GDTF_RDMParam_AttrPDLSize                   "PDLSize"
#define XML_GDTF_RDMParam_AttrDescription               "Description"

#define XML_GDTF_RDMNotifications                       "RDMNotifications"
#define XML_GDTF_RDMNotification                        "RDMNotification"
//
#define XML_GDTF_RDMAbsentNotification                  "RDMAbsentNotification"
//
#define XML_GDTF_RDMParamNotification                   "RDMParameterNotification"
#define XML_GDTF_RDMParamNotification_AttrPID           "PID"
//
#define XML_GDTF_RDMValueBool                           "RDMValueBool"
#define XML_GDTF_RDMValueBool_AttrValue                 "Value"
#define XML_GDTF_RDMValueBool_AttrThresholdOperator     "ThresholdOperator"
// Numeric Vals
#define XML_GDTF_RDMValue_Numeric_AttrValue                     "Value"
#define XML_GDTF_RDMValue_Numeric_AttrThresholdOperator         "ThresholdOperator"
//
#define XML_GDTF_RDMValue_UNSIGNED_BYTE                 "RDMValue_UNSIGNED_BYTE"
#define XML_GDTF_RDMValue_SIGNED_BYTE                   "RDMValue_SIGNED_BYTE"
#define XML_GDTF_RDMValue_UNSIGNED_WORD                 "RDMValue_UNSIGNED_WORD"
#define XML_GDTF_RDMValue_SIGNED_WORD                   "RDMValue_SIGNED_WORD"
#define XML_GDTF_RDMValue_UNSIGNED_DWORD                "RDMValue_UNSIGNED_DWORD"
#define XML_GDTF_RDMValue_SIGNED_DWORD                  "RDMValue_SIGNED_DWORD"
#define XML_GDTF_RDMValue_ASCII                         "RDMValue_ASCII"
//
#define XML_GDTF_RDMValue_SLOT_INFO                     "RDMValue_SLOT_INFO" 
#define XML_GDTF_RDMValue_SLOT_INFO_AttrOffset          "Offset"
#define XML_GDTF_RDMValue_SLOT_INFO_AttrType            "Type"
#define XML_GDTF_RDMValue_SLOT_INFO_AttrSlotLabelID     "SlotLabelID"
//
#define XML_GDTF_RDMValue_STATUS_ID_DESCRIPTION                  "RDMValue_STATUS_ID_DESCRIPTION"
#define XML_GDTF_RDMValue_STATUS_ID_DESCRIPTION_AttrStatusID     "StatusID"
#define XML_GDTF_RDMValue_STATUS_ID_DESCRIPTION_AttrDescription  "Description"
//
#define XML_GDTF_RDMValue_SENSOR_DEFINITION                                     "RDMValue_SENSOR_DEFINITION"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_AttrType                            "Type"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_AttrUnit                            "Unit"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_AttrPrefix                          "Prefix"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_AttrRangeMinValue                   "RangeMinValue"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_AttrRangeMaxValue                   "RangeMaxValue"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_AttrNormalMinValue                  "NormalMinValue"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_AttrNormalMaxValue                  "NormalMaxValue"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_AttrLowesHighestDetectionSupported  "LowesHighestDetectionSupported"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_AttrRecordValueSupported            "RecordValueSupported"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_Attr_Description                     "Description"
// Enum
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_TEMPERATURE  "SEND_TEMPERATURE"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_VOLTAGE      "SEND_VOLTAGE"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_CURRENT      "SEND_CURRENT"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_FREQUENCY    "SEND_FREQUENCY"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_RESISTANCE   "SEND_RESISTANCE"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_POWER        "SEND_POWER"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_MASS         "SEND_MASS"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_LENGTH       "SEND_LENGTH"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_AREA         "SEND_AREA"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_VOLUME       "SEND_VOLUME"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_DENSITY      "SEND_DENSITY"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_VELOCITY     "SEND_VELOCITY"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_ACCELERATION "SEND_ACCELERATION"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_FORCE        "SEND_FORCE"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_ENERGY       "SEND_ENERGY"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_PRESSURE     "SEND_PRESSURE"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_TIME         "SEND_TIME"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_ANGLE        "SEND_ANGLE"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_POSITION_X         "SEND_POSITION_X"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_POSITION_Y         "SEND_POSITION_Y"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_POSITION_Z         "SEND_POSITION_Z"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_ANGULAR_VELOCITY   "SEND_ANGULAR_VELOCITY"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_LUMINOUS_INTENSITY "SEND_LUMINOUS_INTENSITY"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_LUMINOUS_FLUX      "SEND_LUMINOUS_FLUX"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_ILLUMINANCE        "SEND_ILLUMINANCE"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_CHROMINANCE_RED    "SEND_CHROMINANCE_RED"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_CHROMINANCE_GREEN  "SEND_CHROMINANCE_GREEN"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_CHROMINANCE_BLUE    "SEND_CHROMINANCE_BLUE"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_CONTACTS            "SEND_CONTACTS"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_MEMORY              "SEND_MEMORY"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_ITEMS               "SEND_ITEMS"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_HUMIDITY            "SEND_HUMIDITY"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_COUNTER_16BIT       "SEND_COUNTER_16BIT"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_OTHER               "SEND_OTHER"
#define XML_GDTF_RDMValue_SENSOR_DEFINITION_TYPE_ENUM_SEND_MS                  "SEND_MS"
//
#define XML_GDTF_RDMValue_LowesHighestDetectionSupported_ENUM_YES              "YES"
#define XML_GDTF_RDMValue_LowesHighestDetectionSupported_ENUM_NO               "NO"
//
#define XML_GDTF_RDMValue_RecordValueSupported_ENUM_YES                        "YES"
#define XML_GDTF_RDMValue_RecordValueSupported_ENUM_NO                         "NO"
//
#define XML_GDTF_SLOT_INFO_Type_ENUM_ST_PRIMARY          "ST_PRIMARY"
#define XML_GDTF_SLOT_INFO_Type_ENUM_ST_SEC_FINE         "ST_SEC_FINE"
#define XML_GDTF_SLOT_INFO_Type_ENUM_ST_SEC_TIMING       "ST_SEC_TIMING"
#define XML_GDTF_SLOT_INFO_Type_ENUM_ST_SEC_SPEED        "ST_SEC_SPEED"
#define XML_GDTF_SLOT_INFO_Type_ENUM_ST_SEC_CONTROL      "ST_SEC_CONTROL"
#define XML_GDTF_SLOT_INFO_Type_ENUM_ST_SEC_INDEX        "ST_SEC_INDEX"
#define XML_GDTF_SLOT_INFO_Type_ENUM_ST_SEC_ROTATION     "ST_SEC_ROTATION"
#define XML_GDTF_SLOT_INFO_Type_ENUM_ST_SEC_INDEX_ROTATE "ST_SEC_INDEX_ROTATE"
#define XML_GDTF_SLOT_INFO_Type_ENUM_ST_SEC_UNDEFINED    "ST_SEC_UNDEFINED"
//
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_INTENSITY                "SD_INTENSITY"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_INTENSITY_MASTER         "SD_INTENSITY_MASTER"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_PAN                      "SD_PAN"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_TILT                     "SD_TILT"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_WHEEL              "SD_COLOR_WHEEL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_SUB_CYAN           "SD_COLOR_SUB_CYAN"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_SUB_YELLOW         "SD_COLOR_SUB_YELLOW"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_SUB_MAGENTA        "SD_COLOR_SUB_MAGENTA"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_ADD_RED            "SD_COLOR_ADD_RED"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_ADD_GREEN          "SD_COLOR_ADD_GREEN"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_ADD_BLUE           "SD_COLOR_ADD_BLUE"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_CORRECTION         "SD_COLOR_CORRECTION"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_SCROLL             "SD_COLOR_SCROLL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_SEMAPHORE          "SD_COLOR_SEMAPHORE"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_ADD_AMBER          "SD_COLOR_ADD_AMBER"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_ADD_WHITE          "SD_COLOR_ADD_WHITE"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_ADD_WARM_WHITE     "SD_COLOR_ADD_W_ARM_WHITE" // XXX WhiteSpace in the DOCU!!! "SD_COLOR_ADD_W ARM_WHITE"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_ADD_COOL_WHITE     "SD_COLOR_ADD_COOL_WHITE"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_SUB_UV             "SD_COLOR_SUB_UV"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_HUE                "SD_COLOR_HUE"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_COLOR_SATURATION         "SD_COLOR_SATURATION"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_STATIC_GOBO_WHEEL        "SD_STATIC_GOBO_WHEEL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_ROTO_GOBO_WHEEL          "SD_ROTO_GOBO_WHEEL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_PRISM_WHEEL              "SD_PRISM_WHEEL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_EFFECTS_WHEEL            "SD_EFFECTS_WHEEL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_BEAM_SIZE_IRIS           "SD_BEAM_SIZE_IRIS"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_EDGE                     "SD_EDGE"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_FROST                    "SD_FROST"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_STROBE                   "SD_STROBE"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_ZOOM                     "SD_ZOOM"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_FRAMING_SHUTTER          "SD_FRAMING_SHUTTER"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_SHUTTER_ROTATE           "SD_SHUTTER_ROTATE"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_DOUSER                   "SD_DOUSER"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_BARN_DOOR                "SD_BARN_DOOR"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_LAMP_CONTROL             "SD_LAMP_CONTROL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_FIXTURE_CONTROL          "SD_FIXTURE_CONTROL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_FIXTURE_SPEED            "SD_FIXTURE_SPEED"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_MACRO                    "SD_MACRO"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_POWER_CONTROL            "SD_POWER_CONTROL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_FAN_CONTROL              "SD_FAN_CONTROL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_HEATER_CONTROL           "SD_HEATER_CONTROL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_FOUNTAIN_CONTROL         "SD_FOUNTAIN_CONTROL"
#define XML_GDTF_SLOT_INFO_SlotLabelID_ENUM_SD_UNDEFINED                "SD_UNDEFINED"
//
#define XML_GDTF_RDMValue_DMX_PERSONALITY_DESCRIPTION      "RDMValue_DMX_PERSONALITY_DESCRIPTION"
#define XML_GDTF_RDMValue_DMX_PERSON_DESC_AttrFootPrint    "FootPrint"
#define XML_GDTF_RDMValue_DMX_PERSON_DESC_AttrDescription  "Description"

#define XML_GDTF_RDMValue_REAL_TIME_CLOCK                       "RDMValue_REAL_TIME_CLOCK"    
#define XML_GDTF_RDMValue_REAL_TIME_CLOCK_AttrYear              "Year"
#define XML_GDTF_RDMValue_REAL_TIME_CLOCK_AttrMonth             "Month"
#define XML_GDTF_RDMValue_REAL_TIME_CLOCK_AttrDay 	            "Day"
#define XML_GDTF_RDMValue_REAL_TIME_CLOCK_AttrHours             "Hours"
#define XML_GDTF_RDMValue_REAL_TIME_CLOCK_AttrMinute            "Minute"
#define XML_GDTF_RDMValue_REAL_TIME_CLOCK_AttrSecond            "Second"
#define XML_GDTF_RDMValue_REAL_TIME_CLOCK_AttrThresholdOperator "ThresholdOperator"
//
#define XML_GDTF_RDMSensorNotification                   "RDMSensorNotification"
#define XML_GDTF_RDMSensorNotif_AttrSensorOffset         "SensorOffset"
//
#define XML_GDTF_RDMValueSensor                          "ValueSensor"
#define XML_GDTF_RDMValueSensorAttrValue                 "Value"
#define XML_GDTF_RDMValueSensor_AttrLowest               "Lowest"
#define XML_GDTF_RDMValueSensor_AttrHighest              "Highest"
#define XML_GDTF_RDMValueSensor_AttrRecorded             "Recorded"
#define XML_GDTF_RDMValueSensor_AttrThresholdOperator    "ThresholdOperator"
//
#define XML_GDTF_ArtNet                                  "Art-Net"
#define XML_GDTF_sACN                                    "sACN"
#define XML_GDTF_KiNET                                   "KiNET"
#define XML_GDTF_PosiStageNet                            "PosiStageNet"
#define XML_GDTF_OpenSoundControl                        "OpenSoundControl"
#define XML_GDTF_CITP                                    "CITP"
// Enums
#define XML_GDTF_RDMParamTypeEnum_RDM "RDM"
#define XML_GDTF_RDMParamTypeEnum_FixtureType "FixtureType"
#define XML_GDTF_RDMParamTypeEnum_Fixture "Fixture"
//
#define XML_GDTF_RDMParam_DataTypeEnum_DS_NOT_DEFINED    "DS_NOT_DEFINED"
#define XML_GDTF_RDMParam_DataTypeEnum_DS_BIT_FIELD      "DS_BIT_FIELD"
#define XML_GDTF_RDMParam_DataTypeEnum_DS_ASCII          "DS_ASCII"
#define XML_GDTF_RDMParam_DataTypeEnum_DS_UNSIGNED_BYTE  "DS_UNSIGNED_BYTE"
#define XML_GDTF_RDMParam_DataTypeEnum_DS_SIGNED_BYTE    "DS_SIGNED_BYTE"
#define XML_GDTF_RDMParam_DataTypeEnum_DS_UNSIGNED_WORD  "DS_UNSIGNED_WORD"
#define XML_GDTF_RDMParam_DataTypeEnum_DS_SIGNED_WORD    "DS_SIGNED_WORD"
#define XML_GDTF_RDMParam_DataTypeEnum_DS_UNSIGNED_DWORD "DS_UNSIGNED_DWORD"
#define XML_GDTF_RDMParam_DataTypeEnum_DS_SIGNED_DWORD   "DS_SIGNED_DWORD"
#define XML_GDTF_RDMParam_DataTypeEnum_DS_MS             "DS_MS"
//
#define XML_GDTF_RDMParam_Command_None                   "None"
#define XML_GDTF_RDMParam_Command_CC_GET                 "CC_GET"
#define XML_GDTF_RDMParam_Command_CC_SET                 "CC_SET"
#define XML_GDTF_RDMParam_Command_CC_GET_SET             "CC_GET_SET"
//
#define XML_GDTF_RDMParam_SensorUnit_UNITS_NONE "UNITS_NONE"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_CENTIGRADE "UNITS_CENTIGRADE"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_VOLTS_DC "UNITS_VOLTS_DC"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_VOLTS_AC_PEAK "UNITS_VOLTS_AC_PEAK"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_VOLTS_AC_RMS "UNITS_VOLTS_AC_RMS"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_AMPERE_DC "UNITS_AMPERE_DC"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_AMPERE_AC_PEAK "UNITS_AMPERE_AC_PEAK"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_AMPERE_AC_RMS "UNITS_AMPERE_AC_RMS"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_HERTZ "UNITS_HERTZ"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_OHM "UNITS_OHM"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_WATT "UNITS_WATT"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_KILOGRAM "UNITS_KILOGRAM"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_METERS "UNITS_METERS"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_METERS_SQUARED "UNITS_METERS_SQUARED"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_METERS_CUBED "UNITS_METERS_CUBED"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_KILOGRAMMES_PER_METER_CUBED "UNITS_KILOGRAMMES_PER_METER_CUBED"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_METERS_PER_SECOND "UNITS_METERS_PER_SECOND"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_METERS_PER_SECOND_SQUARED "UNITS_METERS_PER_SECOND_SQUARED"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_NEWTON "UNITS_NEWTON"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_JOULE "UNITS_JOULE"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_PASCAL "UNITS_PASCAL"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_SECOND "UNITS_SECOND"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_DEGREE "UNITS_DEGREE"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_STERADIAN "UNITS_STERADIAN"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_CANDELA "UNITS_CANDELA"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_LUMEN "UNITS_LUMEN"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_LUX "UNITS_LUX"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_IRE "UNITS_IRE"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_BYTE "UNITS_BYTE"
#define XML_GDTF_RDMParam_SensorUnit_UNITS_MS "UNITS_MS"
//
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_NONE "PREFIX_NONE"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_DECI "PREFIX_DECI"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_CENTI "PREFIX_CENTI"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_MILLI "PREFIX_MILLI"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_MICRO "PREFIX_MICRO"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_NANO "PREFIX_NANO"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_PICO "PREFIX_PICO"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_FEMPTO "PREFIX_FEMPTO"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_ATTO "PREFIX_ATTO"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_ZEPTO "PREFIX_ZEPTO"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_YOCTO "PREFIX_YOCTO"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_DECA "PREFIX_DECA"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_HECTO "PREFIX_HECTO"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_KILO "PREFIX_KILO"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_MEGA "PREFIX_MEGA"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_GIGA "PREFIX_GIGA"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_TERRA "PREFIX_TERRA"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_PETA "PREFIX_PETA"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_EXA "PREFIX_EXA"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_ZETTA "PREFIX_ZETTA"
#define XML_GDTF_RDMParam_SensorUnitPrefix_PREFIX_YOTTA "PREFIX_YOTTA"
//
#define XML_GDTF_RDMValueBool_Value_YES                 "Yes"
#define XML_GDTF_RDMValueBool_Value_NO                  "No"
// 
#define XML_GDTF_ThresholdOperator_Is                   "Is"
#define XML_GDTF_ThresholdOperator_IsNot                "IsNot"
#define XML_GDTF_ThresholdOperator_Greater              "Greater"
#define XML_GDTF_ThresholdOperator_Less                 "Less"
// -------------------------------------------------------------------------------
#define XML_GDTF_MacroNodeName							"FTMacro"
#define XML_GDTF_UserPresetNodeName						"FTPreset"

#define XML_GDTF_PhysicalDescriptionsEmitterCollect		"Emitters"

#define XML_GDTF_EmitterNodeName						"Emitter"
#define XML_GDTF_EmitterName							"Name"
#define XML_GDTF_EmitterColor							"Color"

#define XML_GDTF_DMX_ProfileCollect                     "DMXProfiles"
#define XML_GDTF_DMX_Profile                            "DMXProfile"

#define XML_GDTF_MeasurementNodeName					"Measurement"
#define XML_GDTF_MeasurementWaveLegth					"WaveLength"
#define XML_GDTF_MeasurementEnergy						"Energy"

#define XML_GDTF_ColorRenderingIndexCollect             "CRIs"
#define XML_GDTF_ColorRenderingIndexGroup               "CRIGroup"
#define XML_GDTF_ColorRenderingIndexGrou_AttrColorTemp  "ColorTemperature"
#define XML_GDTF_ColorRenderingIndex                    "CRI"			
#define XML_GDTF_ColorRenderingIndex_AttrCES            "CES"
#define XML_GDTF_ColorRenderingIndex_AttrColorTemp      "ColorTemperature"


// ColorSample Array
#define XML_GDTF_ColorSample_1  "CES01"
#define XML_GDTF_ColorSample_2  "CES02"
#define XML_GDTF_ColorSample_3  "CES03"
#define XML_GDTF_ColorSample_4  "CES04"
#define XML_GDTF_ColorSample_5  "CES05"
#define XML_GDTF_ColorSample_6  "CES06"
#define XML_GDTF_ColorSample_7  "CES07"
#define XML_GDTF_ColorSample_8  "CES08"
#define XML_GDTF_ColorSample_9  "CES09"
#define XML_GDTF_ColorSample_10 "CES10"
#define XML_GDTF_ColorSample_11 "CES11"
#define XML_GDTF_ColorSample_12 "CES12"
#define XML_GDTF_ColorSample_13 "CES13"
#define XML_GDTF_ColorSample_14 "CES14"
#define XML_GDTF_ColorSample_15 "CES15"
#define XML_GDTF_ColorSample_16 "CES16"
#define XML_GDTF_ColorSample_17 "CES17"
#define XML_GDTF_ColorSample_18 "CES18"
#define XML_GDTF_ColorSample_19 "CES19"
#define XML_GDTF_ColorSample_20 "CES20"
#define XML_GDTF_ColorSample_21 "CES21"
#define XML_GDTF_ColorSample_22 "CES22"
#define XML_GDTF_ColorSample_23 "CES23"
#define XML_GDTF_ColorSample_24 "CES24"
#define XML_GDTF_ColorSample_25 "CES25"
#define XML_GDTF_ColorSample_26 "CES26"
#define XML_GDTF_ColorSample_27 "CES27"
#define XML_GDTF_ColorSample_28 "CES28"
#define XML_GDTF_ColorSample_29 "CES29"
#define XML_GDTF_ColorSample_30 "CES30"
#define XML_GDTF_ColorSample_31 "CES31"
#define XML_GDTF_ColorSample_32 "CES32"
#define XML_GDTF_ColorSample_33 "CES33"
#define XML_GDTF_ColorSample_34 "CES34"
#define XML_GDTF_ColorSample_35 "CES35"
#define XML_GDTF_ColorSample_36 "CES36"
#define XML_GDTF_ColorSample_37 "CES37"
#define XML_GDTF_ColorSample_38 "CES38"
#define XML_GDTF_ColorSample_39 "CES39"
#define XML_GDTF_ColorSample_40 "CES40"
#define XML_GDTF_ColorSample_41 "CES41"
#define XML_GDTF_ColorSample_42 "CES42"
#define XML_GDTF_ColorSample_43 "CES43"
#define XML_GDTF_ColorSample_44 "CES44"
#define XML_GDTF_ColorSample_45 "CES45"
#define XML_GDTF_ColorSample_46 "CES46"
#define XML_GDTF_ColorSample_47 "CES47"
#define XML_GDTF_ColorSample_48 "CES48"
#define XML_GDTF_ColorSample_49 "CES49"
#define XML_GDTF_ColorSample_50 "CES50"
#define XML_GDTF_ColorSample_51 "CES51"
#define XML_GDTF_ColorSample_52 "CES52"
#define XML_GDTF_ColorSample_53 "CES53"
#define XML_GDTF_ColorSample_54 "CES54"
#define XML_GDTF_ColorSample_55 "CES55"
#define XML_GDTF_ColorSample_56 "CES56"
#define XML_GDTF_ColorSample_57 "CES57"
#define XML_GDTF_ColorSample_58 "CES58"
#define XML_GDTF_ColorSample_59 "CES59"
#define XML_GDTF_ColorSample_60 "CES60"
#define XML_GDTF_ColorSample_61 "CES61"
#define XML_GDTF_ColorSample_62 "CES62"
#define XML_GDTF_ColorSample_63 "CES63"
#define XML_GDTF_ColorSample_64 "CES64"
#define XML_GDTF_ColorSample_65 "CES65"
#define XML_GDTF_ColorSample_66 "CES66"
#define XML_GDTF_ColorSample_67 "CES67"
#define XML_GDTF_ColorSample_68 "CES68"
#define XML_GDTF_ColorSample_69 "CES69"
#define XML_GDTF_ColorSample_70 "CES70"
#define XML_GDTF_ColorSample_71 "CES71"
#define XML_GDTF_ColorSample_72 "CES72"
#define XML_GDTF_ColorSample_73 "CES73"
#define XML_GDTF_ColorSample_74 "CES74"
#define XML_GDTF_ColorSample_75 "CES75"
#define XML_GDTF_ColorSample_76 "CES76"
#define XML_GDTF_ColorSample_77 "CES77"
#define XML_GDTF_ColorSample_78 "CES78"
#define XML_GDTF_ColorSample_79 "CES79"
#define XML_GDTF_ColorSample_80 "CES80"
#define XML_GDTF_ColorSample_81 "CES81"
#define XML_GDTF_ColorSample_82 "CES82"
#define XML_GDTF_ColorSample_83 "CES83"
#define XML_GDTF_ColorSample_84 "CES84"
#define XML_GDTF_ColorSample_85 "CES85"
#define XML_GDTF_ColorSample_86 "CES86"
#define XML_GDTF_ColorSample_87 "CES87"
#define XML_GDTF_ColorSample_88 "CES88"
#define XML_GDTF_ColorSample_89 "CES89"
#define XML_GDTF_ColorSample_90 "CES90"
#define XML_GDTF_ColorSample_91 "CES91"
#define XML_GDTF_ColorSample_92 "CES92"
#define XML_GDTF_ColorSample_93 "CES93"
#define XML_GDTF_ColorSample_94 "CES94"
#define XML_GDTF_ColorSample_95 "CES95"
#define XML_GDTF_ColorSample_96 "CES96"
#define XML_GDTF_ColorSample_97 "CES97"
#define XML_GDTF_ColorSample_98 "CES98"
#define XML_GDTF_ColorSample_99 "CES99"