name: Build Static Linux

on:
  [workflow_call, workflow_dispatch]

jobs:
  build_artifact:
    runs-on: ubuntu-latest
    name: Export a Linux build as an artifact
    steps:
      - uses: actions/checkout@v4  # https://github.com/nektos/act/issues/307
      - name: Build
        uses: ./.github/actions/build-linux

      - name: Prepare Artifact
        working-directory: libMvrGdtf
        run: |
          mkdir -p output/include
          cp -r src/Include/* output/include/
          
          mkdir -p output/lib
          cp -r libs/* output/lib/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libMVRgdtf-linux
          path: |
            libMvrGdtf/output
