name: Build with Options

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type'
        required: true
        default: 'normal'
        type: choice
        options:
          - normal
          - asan
          - all

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: libMVRGdtf - checkout repository
        uses: actions/checkout@v4
        with:
          path: libMvrGdtf

      - name: Build
        uses: ./libMvrGdtf/.github/actions/build-lib
        with:
          build-type: ${{ inputs.build-type }}
