name: Build Static Linux

on:
  [workflow_call, workflow_dispatch]

jobs:
  build_artifact:
    runs-on: ubuntu-latest
    name: Export a Linux build as an artifact
    steps:
      - name: libMVRGdtf - checkout repository
        uses: actions/checkout@v4
        with:
          path: libMvrGdtf

      - name: Build
        uses: ./libMvrGdtf/.github/actions/build-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libMVRgdtf-linux
          path: |
            libMvrGdtf/output
